### ISSUE TITLE
404: NOT_FOUND

### ISSUE THREAD

**Issue by 1chooo** [drkostas/python_search_engine#2]
Hi! @drkostas I have clicked this url; however, it is not work and shows `404: NOT_FOUND`.
https://github.com/drkostas/python_search_engine/blob/34b8f5416118bd1a581199354695683b6993c3c1/README.md?plain=1#L5

Please feel free to DM me.

BR,
@1chooo

**Comment by drkostas** [comment]
@1chooo you should be able to access the demo at search.gkos.dev
